# .bashrc

[ -n "$PS1" ] && source ~/.bash_profile

#set aliases
alias ll="ls -lG"
alias gitmaster="git pull origin master"
alias gitorigin="git pull origin"
alias gitreset="git reset HEAD~1"
alias fetch="git fetch -p"
alias search="sudo find / -name"
alias server="python -m SimpleHTTPServer 9999"
alias sb="sublime"
alias branch="git checkout -b"
alias start="npm start"
alias installnode="sudo apt-get update ; sudo apt-get install -y python-software-properties python g++ make ; sudo add-apt-repository ppa:chris-lea/node.js ; sudo apt-get update ; sudo apt-get install nodejs"
echo "~/.bashrc alias's set"
